baseURL: "https://localhost/"
languageCode: en-us
title: Isabella Duan
theme: PaperMod

menu:
  main:
    - identifiers: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifiers: archives
      name: Archives
      url: /archives/
      weight: 30

params:
    assets:
        disableFingerprinting: true
    homeInfoParams:
        Title: Isabella Duan
        Content: machines, humans, and institutions thereabouts

    socialIcons: # optional
        - name: email
          url: "mailto:isabelladuan@uchicago.edu"
        - name: twitter
          url: "https://twitter.com/IsabellaDuan"
        - name: linkedin
          url: "https://www.linkedin.com/in/isabella-duan-43021b163/"
