baseURL: "https://isaduan.github.io/isabelladuan.github.io/"
languageCode: en-us
title: Isabella Duan
theme: PaperMod

enableEmoji: true

menu:
  main:
    - identifiers: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifiers: archives
      name: Archives
      url: /archives/
      weight: 30
    - identifiers: search
      name: Search
      url: /search/
      weight: 40

params:
    assets:
        disableFingerprinting: true
    homeInfoParams:
        Title: Isabella Duan
        Content: machines, humans, and institutions thereabouts

    socialIcons: # optional
        - name: email
          url: "mailto:isabelladuan@uchicago.edu"
        - name: twitter
          url: "https://twitter.com/IsabellaDuan"
        - name: linkedin
          url: "https://www.linkedin.com/in/isabella-duan-43021b163/"

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
